import assert from 'node:assert/strict';
import test from 'node:test';

import { importTs } from './load-ts.mjs';

const {
  BACKUP_ARTIFACTS,
  BACKUP_TARGET_PATH,
  backupConfirmationMatches,
  episodeScheduleProjection,
  episodeSectionFromPath,
  episodeSectionPath,
  formatEpisodeTimestamp,
  parseEpisodeTimestamp,
} = await importTs(new URL('../src/lib/episode-release.ts', import.meta.url));

test('backup inventory and target retain the six reviewed items', () => {
  assert.deepEqual(BACKUP_ARTIFACTS, [
    { label: 'Source footage', detail: 'Raw DJI .MP4 + H6E multi-track (.wav)' },
    {
      label: 'Stitched video',
      detail: 'source_merged.mp4 (camera + scratch audio)',
    },
    {
      label: 'Longform render',
      detail: 'longform.mp4 with LUT + crops + enhanced audio',
    },
    { label: 'Shorts', detail: 'Up to 10 × 9:16 captioned clips' },
    {
      label: 'Metadata',
      detail: 'Per-platform titles, descriptions, hashtags',
    },
    {
      label: 'Thumbnails + transcripts',
      detail: 'Generated by the cascade agents',
    },
  ]);
  assert.equal(BACKUP_TARGET_PATH, '/Volumes/Seagate Portable Drive/podcast/');
});

test('maps every consolidated alias to a stable episode section', () => {
  const episodeId = 'episode / 01';
  for (const [section, suffix] of [
    ['review', ''],
    ['audio', '/audio'],
    ['delivery', '/delivery'],
    ['metadata', '/metadata'],
    ['publication', '/publish'],
    ['backup', '/backup'],
  ]) {
    const path = `/episodes/episode%20%2F%2001${suffix}`;
    assert.equal(episodeSectionFromPath(path, episodeId), section);
    assert.equal(episodeSectionFromPath(`${path}/`, episodeId), section);
    assert.equal(episodeSectionPath(episodeId, section), path);
  }
});

test('backup approval requires only the exact case-insensitive phrase', () => {
  assert.equal(backupConfirmationMatches(' back it up '), true);
  assert.equal(backupConfirmationMatches('BACK IT UP'), true);
  assert.equal(backupConfirmationMatches('back it up now'), false);
  assert.equal(backupConfirmationMatches(''), false);
});

test('episode timestamps reject invalid and non-finite trim ranges', () => {
  assert.equal(parseEpisodeTimestamp('01:02:03.500'), 3723.5);
  assert.equal(parseEpisodeTimestamp('62.25'), 62.25);
  assert.equal(parseEpisodeTimestamp('00:60'), null);
  assert.equal(parseEpisodeTimestamp('Infinity'), null);
  assert.equal(parseEpisodeTimestamp('1:2:3:4'), null);
  assert.equal(formatEpisodeTimestamp(3723.5), '01:02:03.500');
});

test('schedule projection preserves only canonical evidence for one episode', () => {
  const schedule = {
    schedule: [
      {
        items: [
          {
            episode_id: 'target',
            type: 'short',
            state: 'scheduled',
            artifact_current: false,
          },
          { episode_id: 'other', type: 'short', state: 'published' },
        ],
      },
    ],
    publication_evidence: [
      {
        episode_id: 'target',
        content_type: 'short',
        status: 'submitted',
      },
      {
        episode_id: 'other',
        content_type: 'short',
        status: 'published',
      },
    ],
    held_items: [{ episode_id: 'target', blockers: ['Current quality approval is missing.'] }],
  };

  assert.deepEqual(episodeScheduleProjection(schedule, 'target'), {
    items: [
      {
        episode_id: 'target',
        type: 'short',
        state: 'scheduled',
        artifact_current: false,
      },
    ],
    publicationEvidence: [
      {
        episode_id: 'target',
        content_type: 'short',
        status: 'submitted',
      },
    ],
    blockers: ['Current quality approval is missing.'],
  });
});
