#!/usr/bin/env bash
# Compile corrections JSONL + team/*.md into a flat rules-compiled.md so
# CLAUDE.md can reference it and the rules load into context on session start.
#
# Dedupes by (category, rule) pair — same rule from multiple entries = one line.
# Groups by category.

set -eu

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
MEM_DIR="$REPO_ROOT/.claude/memory"
OUT="$MEM_DIR/rules-compiled.md"

mkdir -p "$MEM_DIR"

python3 - "$MEM_DIR" "$OUT" <<'PY'
import json, os, sys, glob
from collections import defaultdict

mem_dir, out_path = sys.argv[1], sys.argv[2]
corrections_root = os.path.join(mem_dir, "corrections")
team_dir = os.path.join(mem_dir, "team")

# (category, rule) -> {"sources": set, "count": int}
rules = defaultdict(lambda: {"sources": set(), "count": 0})

# Ingest developer corrections
if os.path.isdir(corrections_root):
    for dev in sorted(os.listdir(corrections_root)):
        dev_dir = os.path.join(corrections_root, dev)
        jsonl = os.path.join(dev_dir, "corrections.jsonl")
        if not os.path.isfile(jsonl): continue
        with open(jsonl) as f:
            for line in f:
                line = line.strip()
                if not line: continue
                try:
                    rec = json.loads(line)
                except: continue
                key = (rec.get("category","uncategorized"), rec.get("rule","").strip())
                if not key[1]: continue
                rules[key]["sources"].add(f"dev:{dev}")
                rules[key]["count"] += 1

# Ingest team memory files (expected shape: markdown with frontmatter-like lines)
team_rules_by_cat = defaultdict(list)
if os.path.isdir(team_dir):
    for mdfile in sorted(glob.glob(os.path.join(team_dir, "*.md"))):
        slug = os.path.basename(mdfile)[:-3]
        with open(mdfile) as f:
            content = f.read().strip()
        team_rules_by_cat[slug].append(content)

# Emit
lines = []
lines.append("# Compiled Rules\n")
lines.append("Auto-generated by `.claude/scripts/compile-corrections.sh`. Do not edit by hand.\n")
lines.append(f"_Last compiled: {os.popen('date -u +%Y-%m-%dT%H:%M:%SZ').read().strip()}_\n")

if team_rules_by_cat:
    lines.append("\n## Team Memory (shared, in git)\n")
    for cat in sorted(team_rules_by_cat):
        lines.append(f"\n### {cat}\n")
        for body in team_rules_by_cat[cat]:
            lines.append(body + "\n")

if rules:
    lines.append("\n## Developer Corrections (private, compiled)\n")
    by_cat = defaultdict(list)
    for (cat, rule), meta in rules.items():
        by_cat[cat].append((rule, meta))
    for cat in sorted(by_cat):
        lines.append(f"\n### {cat}\n")
        for rule, meta in sorted(by_cat[cat]):
            src_str = ", ".join(sorted(meta["sources"]))
            mult = f" (×{meta['count']})" if meta['count'] > 1 else ""
            lines.append(f"- {rule}{mult} _[{src_str}]_")

if not rules and not team_rules_by_cat:
    lines.append("\n_(No corrections or team memories yet. Emit `[LEARN]` blocks and run `/publish-memory` to populate.)_\n")

with open(out_path, "w") as f:
    f.write("\n".join(lines))

total = len(rules) + sum(len(v) for v in team_rules_by_cat.values())
print(f"compile-corrections: wrote {total} rules/memories to {out_path}")
PY
