/**
 * Backup — copy episode artifacts to the Seagate drive, then optionally
 * clear the SD card. Dangerous-action UI: approve-backup runs the backup
 * agent; SD clear is a separate step behind an explicit "I understand"
 * confirmation.
 */

import { h, mount } from '../lib/dom';
import { signal, effect, type Signal } from '../lib/signals';
import { api, type UnknownRecord } from '../lib/api';
import { describeStatus, episodeTitle, formatDuration } from '../lib/format';
import { StatusPill } from '../components/StatusPill';
import { Button } from '../components/Button';
import { Icon } from '../components/icons';
import { link, navigate } from '../lib/router';
import { showToast } from '../state/ui';

export function Backup(target: HTMLElement, episodeId: string): void {
  const episode = signal<UnknownRecord | null>(null);
  const approving = signal<boolean>(false);
  const confirmPhrase = signal<string>('');

  (async () => {
    try {
      episode.set(await api.getEpisode(episodeId));
    } catch (e) {
      showToast((e as Error).message, 'error');
    }
  })();

  const page = h('div', { class: 'min-h-full' });

  effect(() => {
    const ep = episode();
    if (!ep) {
      page.replaceChildren(
        h(
          'div',
          { class: 'px-10 py-10' },
          h('div', { class: 'panel h-64 animate-pulse-breath' })
        )
      );
      return;
    }
    page.replaceChildren(renderPage(episodeId, ep, approving, confirmPhrase));
  });

  mount(target, page);
}

function renderPage(
  episodeId: string,
  ep: UnknownRecord,
  approving: Signal<boolean>,
  confirmPhrase: Signal<string>
): HTMLElement {
  const status = describeStatus(ep.status as string);
  const title = episodeTitle(ep, episodeId);
  const canBackup = status.key === 'awaiting_backup';
  const expectedPhrase = 'back it up';

  const approveBtn = h('div');
  effect(() => {
    const busy = approving();
    const match = confirmPhrase().trim().toLowerCase() === expectedPhrase;
    approveBtn.replaceChildren(
      Button({
        variant: 'primary',
        size: 'lg',
        label: busy ? 'Backing up…' : 'Back it up',
        loading: busy,
        disabled: !match || busy,
        onClick: async () => {
          approving.set(true);
          try {
            await api.approveBackup(episodeId);
            showToast(
              'Backup started — pipeline is copying to Seagate.',
              'success'
            );
            navigate(`/episodes/${episodeId}`);
          } catch (e) {
            showToast((e as Error).message, 'error');
          } finally {
            approving.set(false);
          }
        },
      })
    );
  });

  const confirmInput = h('input', {
    type: 'text',
    placeholder: `Type "${expectedPhrase}" to enable the button`,
    class:
      'w-full h-11 bg-surface-2 border border-border rounded-md px-4 text-body text-ink-primary placeholder:text-ink-disabled focus:border-accent focus:outline-none',
    oninput: (e: Event) =>
      confirmPhrase.set((e.target as HTMLInputElement).value),
  });

  const artifactRows: Array<{ label: string; detail: string }> = [
    { label: 'Source footage', detail: 'Raw DJI .MP4 + H6E multi-track (.wav)' },
    { label: 'Stitched video', detail: 'source_merged.mp4 (camera + scratch audio)' },
    { label: 'Longform render', detail: 'longform.mp4 with LUT + crops + enhanced audio' },
    { label: 'Shorts', detail: 'Up to 10 × 9:16 captioned clips' },
    { label: 'Metadata', detail: 'Per-platform titles, descriptions, hashtags' },
    { label: 'Thumbnails + transcripts', detail: 'Generated by the cascade agents' },
  ];

  return h(
    'div',
    { class: 'max-w-[860px] mx-auto px-10 py-12 flex flex-col gap-6' },
    h(
      'a',
      {
        ...link(`/episodes/${episodeId}`),
        class:
          'inline-flex items-center gap-1 text-body-sm text-ink-tertiary hover:text-ink-primary mb-2',
      },
      Icon.chevronLeft({ size: 14 }),
      'Back to episode'
    ),
    h(
      'div',
      null,
      h(
        'div',
        { class: 'flex items-center gap-3 mb-2' },
        h(
          'span',
          { class: 'text-heading-sm uppercase text-ink-tertiary' },
          'Backup'
        ),
        StatusPill({ descriptor: status, size: 'sm' })
      ),
      h(
        'h1',
        { class: 'font-display text-display-xl text-ink-primary' },
        title
      )
    ),
    h(
      'div',
      {
        class: 'grid grid-cols-[1.6fr_1fr] gap-6',
      },
      // Left: what gets copied
      h(
        'div',
        { class: 'panel p-6 flex flex-col gap-4' },
        h(
          'div',
          { class: 'text-heading-sm uppercase text-ink-tertiary' },
          'What gets copied'
        ),
        h(
          'p',
          { class: 'text-body text-ink-secondary leading-relaxed' },
          'Everything on SSD for this episode is rsync’d to the Seagate drive so the original footage can be freed from the SD cards. Takes 5–15 minutes.'
        ),
        h(
          'div',
          { class: 'flex flex-col divide-y divide-border-subtle' },
          ...artifactRows.map((r) =>
            h(
              'div',
              { class: 'py-2.5' },
              h(
                'div',
                { class: 'text-body text-ink-primary font-medium' },
                r.label
              ),
              h(
                'div',
                { class: 'text-body-sm text-ink-tertiary' },
                r.detail
              )
            )
          )
        )
      ),
      // Right: paths + confirm
      h(
        'div',
        { class: 'flex flex-col gap-4' },
        h(
          'div',
          { class: 'panel p-5 flex flex-col gap-3' },
          h(
            'div',
            { class: 'text-heading-sm uppercase text-ink-tertiary' },
            'Paths'
          ),
          pathRow('Source', `/Volumes/1TB_SSD/cascade/episodes/${episodeId}/`),
          pathRow('Target', '/Volumes/Seagate Portable Drive/podcast/'),
          pathRow('Duration', formatDuration(ep.duration_seconds as number))
        ),
        canBackup
          ? h(
              'div',
              {
                class:
                  'panel p-5 flex flex-col gap-3 border-status-warning/30',
              },
              h(
                'div',
                { class: 'flex items-center gap-2' },
                h('span', {
                  class:
                    'w-2 h-2 rounded-full bg-status-warning shadow-[0_0_8px_rgba(232,176,89,0.4)]',
                }),
                h(
                  'span',
                  { class: 'text-body text-status-warning font-medium' },
                  'Confirm to run'
                )
              ),
              h(
                'p',
                { class: 'text-body-sm text-ink-secondary' },
                'Type ',
                h(
                  'code',
                  {
                    class:
                      'bg-surface-inset px-1.5 py-0.5 rounded text-code-sm text-ink-primary',
                  },
                  expectedPhrase
                ),
                ' to enable the run button.'
              ),
              confirmInput,
              approveBtn
            )
          : h(
              'div',
              { class: 'panel p-5' },
              h(
                'div',
                {
                  class: 'text-body text-ink-primary font-medium mb-1',
                },
                'Not ready yet'
              ),
              h(
                'p',
                { class: 'text-body-sm text-ink-secondary leading-relaxed' },
                `Current status: ${status.label}. ${status.hint}`
              )
            )
      )
    )
  );
}

function pathRow(label: string, value: string): HTMLElement {
  return h(
    'div',
    { class: 'flex flex-col gap-0.5' },
    h(
      'div',
      { class: 'text-body-sm text-ink-tertiary' },
      label
    ),
    h(
      'div',
      {
        class:
          'text-code text-ink-primary font-mono tabular break-all leading-snug',
      },
      value
    )
  );
}

