export type EpisodeSection = 'review' | 'audio' | 'delivery' | 'metadata' | 'publication' | 'backup';

export interface EpisodeScheduleItem extends Record<string, unknown> {
  episode_id: string;
  type: string;
  state?: string;
  scheduled_date?: string;
  destination?: string;
  destinations?: string[];
  clip_id?: string;
  job_id?: string;
  request_id?: string;
  error?: string;
  artifact_current?: boolean | null;
}

export interface EpisodePublicationEvidence extends Record<string, unknown> {
  episode_id: string;
  content_type: string;
  status: string;
  destination?: string;
  destinations?: string[];
  clip_id?: string;
  url?: string;
  scheduled?: boolean;
  job_id?: string;
  request_id?: string;
  error?: string;
}

export interface EpisodeScheduleProjection {
  loaded: boolean;
  items: EpisodeScheduleItem[];
  publicationEvidence: EpisodePublicationEvidence[];
  blockers: string[];
}

export const BACKUP_ARTIFACTS: ReadonlyArray<{
  label: string;
  detail: string;
}> = [
  { label: 'Source footage', detail: 'Raw DJI .MP4 + H6E multi-track (.wav)' },
  {
    label: 'Stitched video',
    detail: 'source_merged.mp4 (camera + scratch audio)',
  },
  {
    label: 'Longform render',
    detail: 'longform.mp4 with LUT + crops + enhanced audio',
  },
  { label: 'Shorts', detail: 'Up to 10 × 9:16 captioned clips' },
  {
    label: 'Metadata',
    detail: 'Per-platform titles, descriptions, hashtags',
  },
  {
    label: 'Thumbnails + transcripts',
    detail: 'Generated by the cascade agents',
  },
];

export const BACKUP_TARGET_PATH = '/Volumes/Seagate Portable Drive/podcast/';

export function episodeSectionFromPath(path: string, episodeId: string): EpisodeSection {
  const base = `/episodes/${encodeURIComponent(episodeId)}`;
  const normalized = path.length > 1 ? path.replace(/\/+$/, '') : path;
  if (normalized === `${base}/audio`) return 'audio';
  if (normalized === `${base}/delivery`) return 'delivery';
  if (normalized === `${base}/metadata`) return 'metadata';
  if (normalized === `${base}/publish`) return 'publication';
  if (normalized === `${base}/backup`) return 'backup';
  return 'review';
}

export function episodeSectionPath(episodeId: string, section: EpisodeSection): string {
  const base = `/episodes/${encodeURIComponent(episodeId)}`;
  if (section === 'review') return base;
  const suffix = section === 'publication' ? 'publish' : section;
  return `${base}/${suffix}`;
}

export function backupConfirmationMatches(value: string): boolean {
  return value.trim().toLowerCase() === 'back it up';
}

export function parseEpisodeTimestamp(value: string): number | null {
  const parts = value.trim().split(':');
  if (!parts.length || parts.length > 3) return null;
  const numbers = parts.map(Number);
  if (numbers.some((part) => !Number.isFinite(part) || part < 0)) return null;
  if (numbers.length === 1) return numbers[0];
  if (numbers.slice(1).some((part) => part >= 60)) return null;
  return numbers.reduce((total, part) => total * 60 + part, 0);
}

export function formatEpisodeTimestamp(value: number): string {
  const hours = Math.floor(value / 3600);
  const minutes = Math.floor((value % 3600) / 60);
  const seconds = value % 60;
  return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${seconds.toFixed(3).padStart(6, '0')}`;
}

export function episodeScheduleProjection(schedule: Record<string, unknown> | null, episodeId: string): EpisodeScheduleProjection {
  if (!schedule) return { loaded: false, items: [], publicationEvidence: [], blockers: [] };
  const items = ((schedule.schedule as Array<Record<string, unknown>>) ?? [])
    .flatMap((day) => (Array.isArray(day.items) ? (day.items as EpisodeScheduleItem[]) : []))
    .filter((item) => item.episode_id === episodeId);
  const publicationEvidence = ((schedule.publication_evidence as EpisodePublicationEvidence[]) ?? []).filter((record) => record.episode_id === episodeId);
  const held = ((schedule.held_items as Array<Record<string, unknown>>) ?? []).find((item) => item.episode_id === episodeId);
  const blockers = Array.isArray(held?.blockers) ? held.blockers.filter((value): value is string => typeof value === 'string') : [];
  return { loaded: true, items, publicationEvidence, blockers };
}
